version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
  dynamodb:
    image: skylarsch/dynamodb-dev:latest
    ports:
      - 8000:8000
    volumes:
      - dynamodb-data:/var/dynamodb_local
  postgres:
    restart: always
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  dynamodb-data:
    driver: local
  postgres-data:
    driver: local
